// <auto-generated>
// Généré par tools/generate-demo-jdv.py à partir des jeux de valeurs ANS du dépôt : ne pas modifier.
// </auto-generated>

namespace CdaCrImg.Demo.Form;

/// <summary>Jeux de valeurs ANS utilisés par les listes déroulantes du formulaire.</summary>
public static class JeuxDeValeurs
{
    /// <summary>JDV_J04_XdsPracticeSettingCode_CISIS (1.2.250.1.213.1.1.5.467) : standardIndustryClassCode.</summary>
    public static readonly IReadOnlyList<Option> SecteurActivite = new Option[]
    {
        new("AMBULATOIRE", "1.2.250.1.213.1.1.4.9", "Ambulatoire"),
        new("AMO", "1.2.250.1.213.1.1.4.9", "Organisme d'assurance maladie obligatoire"),
        new("DEPISTAGE", "1.2.250.1.213.1.1.4.9", "Dépistage"),
        new("ESSMS", "1.2.250.1.213.1.1.4.9", "Etablissement ou Service Social ou Médico-Social"),
        new("ETABLISSEMENT", "1.2.250.1.213.1.1.4.9", "Etablissement de santé"),
        new("HAD", "1.2.250.1.213.1.1.4.9", "Hospitalisation à domicile"),
        new("MAD", "1.2.250.1.213.1.1.4.9", "Maintien à domicile"),
        new("PALLIATIF", "1.2.250.1.213.1.1.4.9", "Soins palliatifs"),
        new("SAD", "1.2.250.1.213.1.1.4.9", "Soins à domicile"),
        new("SAMU_SMUR", "1.2.250.1.213.1.1.4.9", "SAMU/SMUR"),
    };

    /// <summary>JDV_J02_XdsHealthcareFacilityTypeCode_CISIS (1.2.250.1.213.1.1.5.466) : healthCareFacility/code.</summary>
    public static readonly IReadOnlyList<Option> CadreExercice = new Option[]
    {
        new("SA01", "1.2.250.1.71.4.2.4", "Etablissement public de santé"),
        new("SA02", "1.2.250.1.71.4.2.4", "Hôpital militaire du Service de santé des armées"),
        new("SA03", "1.2.250.1.71.4.2.4", "Etablissement privé PSPH"),
        new("SA04", "1.2.250.1.71.4.2.4", "Etablissement privé non PSPH"),
        new("SA05", "1.2.250.1.71.4.2.4", "Centre de santé"),
        new("SA06", "1.2.250.1.71.4.2.4", "Autre structure du Service de santé des armées"),
        new("SA07", "1.2.250.1.71.4.2.4", "Cabinet individuel"),
        new("SA08", "1.2.250.1.71.4.2.4", "Cabinet de groupe"),
        new("SA09", "1.2.250.1.71.4.2.4", "Exercice en société"),
        new("SA10", "1.2.250.1.71.4.2.4", "Transporteur sanitaire"),
        new("SA12", "1.2.250.1.71.4.2.4", "Etablissement de soins et prévention"),
        new("SA13", "1.2.250.1.71.4.2.4", "Prévention et soins en entreprise"),
        new("SA14", "1.2.250.1.71.4.2.4", "Etablissements scolaires, universitaires et de formation hors champ FINESS"),
        new("SA15", "1.2.250.1.71.4.2.4", "PMI et Planification familiale"),
        new("SA16", "1.2.250.1.71.4.2.4", "Etablissement pour personnes handicapées"),
        new("SA17", "1.2.250.1.71.4.2.4", "Etablissement pour personnes âgées"),
        new("SA18", "1.2.250.1.71.4.2.4", "Etablissement aide à la famille"),
        new("SA19", "1.2.250.1.71.4.2.4", "Etablissements FINESS de formation aux professions sanitaires et sociales"),
        new("SA20", "1.2.250.1.71.4.2.4", "Etablissement pour la protection de l'enfance"),
        new("SA21", "1.2.250.1.71.4.2.4", "Etablissement d'hébergement et de réadaptation"),
        new("SA22", "1.2.250.1.71.4.2.4", "Recherche"),
        new("SA23", "1.2.250.1.71.4.2.4", "Assurance privée"),
        new("SA24", "1.2.250.1.71.4.2.4", "Organisme de sécurité sociale"),
        new("SA25", "1.2.250.1.71.4.2.4", "Laboratoire de biologie médicale"),
        new("SA26", "1.2.250.1.71.4.2.4", "Ministère ou Service déconcentré"),
        new("SA27", "1.2.250.1.71.4.2.4", "Collectivité territoriale"),
        new("SA28", "1.2.250.1.71.4.2.4", "Association ou organisme humanitaire"),
        new("SA29", "1.2.250.1.71.4.2.4", "Laboratoire d'analyses et de biologie médicale"),
        new("SA30", "1.2.250.1.71.4.2.4", "Autre établissement sanitaire"),
        new("SA31", "1.2.250.1.71.4.2.4", "Répartition et Distribution de médicaments et dispositifs médicaux"),
        new("SA32", "1.2.250.1.71.4.2.4", "Fabrication, Exploitation et Importation de médicaments et dispositifs médicaux"),
        new("SA33", "1.2.250.1.71.4.2.4", "Pharmacie d'officine"),
        new("SA34", "1.2.250.1.71.4.2.4", "Centre de dialyse"),
        new("SA35", "1.2.250.1.71.4.2.4", "Para-pharmacie"),
        new("SA36", "1.2.250.1.71.4.2.4", "Centre anti-cancer"),
        new("SA37", "1.2.250.1.71.4.2.4", "Centre de transfusion sanguine"),
        new("SA38", "1.2.250.1.71.4.2.4", "Pharmacie minière"),
        new("SA39", "1.2.250.1.71.4.2.4", "Pharmacie mutualiste"),
        new("SA40", "1.2.250.1.71.4.2.4", "Secteur privé, praticien hospitalier temps plein"),
        new("SA41", "1.2.250.1.71.4.2.4", "Autre établissement du domaine social ou médico-social"),
        new("SA42", "1.2.250.1.71.4.2.4", "Appareillage médical"),
        new("SA43", "1.2.250.1.71.4.2.4", "Secteur non défini"),
        new("SA44", "1.2.250.1.71.4.2.4", "Recrutement ou Gestion RH"),
        new("SA45", "1.2.250.1.71.4.2.4", "Communication, Marketing, Consulting, Média"),
        new("SA46", "1.2.250.1.71.4.2.4", "Fabrication, Exploitation, Importation, Répartition, Distribution médicaments et dispositifs médicaux"),
        new("SA47", "1.2.250.1.71.4.2.4", "Incendie et secours"),
        new("SA48", "1.2.250.1.71.4.2.4", "Entreprise industrielle et tertiaire hors industrie pharmaceutique"),
        new("SA49", "1.2.250.1.71.4.2.4", "Entité Outre-Mer"),
        new("SA50", "1.2.250.1.71.4.2.4", "Permanence des soins ambulatoires hors cabinet"),
        new("SA51", "1.2.250.1.71.4.2.4", "Structure de coopération avec autorisation de soins"),
        new("SA52", "1.2.250.1.71.4.2.4", "Maison de santé ou Pôle de santé"),
        new("SA53", "1.2.250.1.71.4.2.4", "Siège administratif d'un établissement de santé"),
        new("SA54", "1.2.250.1.71.4.2.4", "Centre de dépistage et de prévention"),
        new("SA55", "1.2.250.1.71.4.2.4", "Laboratoire pharmaceutique préparant et délivrant des allergènes"),
        new("SA56", "1.2.250.1.71.4.2.4", "Propharmacie"),
        new("SA57", "1.2.250.1.71.4.2.4", "Structure de coopération avec mission de coordination de soins"),
        new("SA58", "1.2.250.1.71.4.2.4", "Entreprise de taxis"),
        new("SA59", "1.2.250.1.71.4.2.4", "Laboratoire de biologie médicale hors catégorie standard"),
        new("SA60", "1.2.250.1.71.4.2.4", "Centres médicaux SNCF"),
        new("SA61", "1.2.250.1.71.4.2.4", "Structure Dispensatrice à domicile d'Oxygène à usage médical"),
        new("SA63", "1.2.250.1.71.4.2.4", "Structures de coordination et d'orientation"),
        new("SA64", "1.2.250.1.71.4.2.4", "Société de téléconsultation"),
        new("SA65", "1.2.250.1.71.4.2.4", "Antenne de pharmacie"),
        new("SA66", "1.2.250.1.71.4.2.4", "Services de Prévention et de Santé au Travail (SPST)"),
        new("SA67", "1.2.250.1.71.4.2.4", "Maisons médicales de garde (MMG)"),
        new("SA68", "1.2.250.1.71.4.2.4", "Services départementaux d'incendie et de secours"),
        new("SA69", "1.2.250.1.71.4.2.4", "Maisons de naissance"),
    };

    /// <summary>JDV_J142_TypeRencontre_CISIS (1.2.250.1.213.1.1.5.589) : encompassingEncounter/code.</summary>
    public static readonly IReadOnlyList<Option> TypeRencontre = new Option[]
    {
        new("IMP", "2.16.840.1.113883.5.4", "Hospitalisation (établissement, y compris HAD)"),
        new("EMER", "2.16.840.1.113883.5.4", "Passage aux urgences (établissement)"),
        new("AMB", "2.16.840.1.113883.5.4", "Ambulatoire (hors établissement)"),
        new("FLD", "2.16.840.1.113883.5.4", "Terrain (voie publique, hélicoptère, ambulance, etc.)"),
        new("HH", "2.16.840.1.113883.5.4", "Soins à domicile (hors établissement)"),
        new("VR", "2.16.840.1.113883.5.4", "Virtuelle (exemple : RCP en l'absence du patient)"),
        new("EXTERNE", "1.2.250.1.213.1.1.4.2.291", "Acte et consultation externe (établissement)"),
        new("SEANCE", "1.2.250.1.213.1.1.4.2.291", "Séance (établissement ou libéral)"),
    };

    /// <summary>JDV_J245_Civilite_CISIS (1.2.250.1.213.1.1.5.718) : name/prefix.</summary>
    public static readonly IReadOnlyList<Option> Civilite = new Option[]
    {
        new("M", "1.2.250.1.213.1.6.1.69", "Monsieur"),
        new("MME", "1.2.250.1.213.1.6.1.69", "Madame"),
    };

    /// <summary>JDV_J246_Titre_CISIS (1.2.250.1.213.1.1.5.719) : name/suffix.</summary>
    public static readonly IReadOnlyList<Option> Titre = new Option[]
    {
        new("DR", "1.2.250.1.213.1.6.1.11", "Docteur"),
        new("MC", "1.2.250.1.213.1.6.1.11", "Médecin chef"),
        new("MG", "1.2.250.1.213.1.6.1.11", "Médecin général"),
        new("PC", "1.2.250.1.213.1.6.1.11", "Pharmacien chef"),
        new("PG", "1.2.250.1.213.1.6.1.11", "Pharmacien général"),
        new("PR", "1.2.250.1.213.1.6.1.11", "Professeur"),
    };

    /// <summary>JDV_J47_FunctionCode_CISIS (1.2.250.1.213.1.1.5.124) : author/functionCode.</summary>
    public static readonly IReadOnlyList<Option> FonctionAuteur = new Option[]
    {
        new("ADMPHYS", "2.16.840.1.113883.5.88", "Responsable de l'admission"),
        new("ATTPHYS", "2.16.840.1.113883.5.88", "Référent - Responsable du patient dans la structure de soins"),
        new("DISPHYS", "2.16.840.1.113883.5.88", "Responsable de la sortie"),
        new("PCP", "2.16.840.1.113883.5.88", "Médecin traitant"),
    };

    /// <summary>jdv-modalite-acquisition-cisis (1.2.250.1.213.1.1.5.618) : modalité d'acquisition DICOM.</summary>
    public static readonly IReadOnlyList<Option> ModaliteAcquisition = new Option[]
    {
        new("AR", "1.2.840.10008.2.16.4", "Autoréfraction"),
        new("BDUS", "1.2.840.10008.2.16.4", "Échodensitométrie osseuse"),
        new("BI", "1.2.840.10008.2.16.4", "Imagerie biomagnétique"),
        new("BMD", "1.2.840.10008.2.16.4", "Ostéodensitométrie"),
        new("CR", "1.2.840.10008.2.16.4", "Radiographie assistée par ordinateur"),
        new("CT", "1.2.840.10008.2.16.4", "Tomodensitométrie"),
        new("DG", "1.2.840.10008.2.16.4", "Diaphanographie"),
        new("DMS", "1.2.840.10008.2.16.4", "Dermoscopie"),
        new("DX", "1.2.840.10008.2.16.4", "Radiographie numérique"),
        new("ECG", "1.2.840.10008.2.16.4", "Électrocardiographie"),
        new("EEG", "1.2.840.10008.2.16.4", "Électroencéphalographie"),
        new("EMG", "1.2.840.10008.2.16.4", "Électromyographie"),
        new("EOG", "1.2.840.10008.2.16.4", "Électrooculographie"),
        new("EPS", "1.2.840.10008.2.16.4", "Électrophysiologie cardiaque"),
        new("ES", "1.2.840.10008.2.16.4", "Endoscopie"),
        new("GM", "1.2.840.10008.2.16.4", "Microscopie générale"),
        new("HD", "1.2.840.10008.2.16.4", "Onde hémodynamique"),
        new("IO", "1.2.840.10008.2.16.4", "Radiographie intrabuccale"),
        new("IVOCT", "1.2.840.10008.2.16.4", "Tomographie par cohérence optique intravasculaire"),
        new("IVUS", "1.2.840.10008.2.16.4", "Ultrasonore intravasculaire"),
        new("KER", "1.2.840.10008.2.16.4", "Kératométrie"),
        new("LEN", "1.2.840.10008.2.16.4", "Lensométrie"),
        new("LS", "1.2.840.10008.2.16.4", "Scan laser"),
        new("MG", "1.2.840.10008.2.16.4", "Mammographie"),
        new("MR", "1.2.840.10008.2.16.4", "Résonance magnétique"),
        new("NM", "1.2.840.10008.2.16.4", "Médecine nucléaire"),
        new("OAM", "1.2.840.10008.2.16.4", "Mesures axiales ophtalmiques"),
        new("OCT", "1.2.840.10008.2.16.4", "Tomographie à cohérence optique"),
        new("OP", "1.2.840.10008.2.16.4", "Photographique ophtalmique"),
        new("OPM", "1.2.840.10008.2.16.4", "Cartographie ophtalmique"),
        new("OPT", "1.2.840.10008.2.16.4", "Tomographie ophtalmique"),
        new("OPTBSV", "1.2.840.10008.2.16.4", "Tomographie ophtalmique B-scan analyse de volume"),
        new("OPTENF", "1.2.840.10008.2.16.4", "Tomographie ophtalmique en face"),
        new("OPV", "1.2.840.10008.2.16.4", "Champ visuel ophtalmique"),
        new("OSS", "1.2.840.10008.2.16.4", "Scanner optique de surface"),
        new("POS", "1.2.840.10008.2.16.4", "Détecteur de position"),
        new("PT", "1.2.840.10008.2.16.4", "TEP : Tomographie par émission de positons"),
        new("PX", "1.2.840.10008.2.16.4", "Panaromique X-Ray"),
        new("RESP", "1.2.840.10008.2.16.4", "Onde respiratoire"),
        new("RF", "1.2.840.10008.2.16.4", "Radio-fluoroscopie"),
        new("RG", "1.2.840.10008.2.16.4", "Imagerie radiographique"),
        new("RTIMAGE", "1.2.840.10008.2.16.4", "Image RT"),
        new("SM", "1.2.840.10008.2.16.4", "Microscopie à lames"),
        new("SRF", "1.2.840.10008.2.16.4", "Réfraction subjective"),
        new("TG", "1.2.840.10008.2.16.4", "Thermographie"),
        new("US", "1.2.840.10008.2.16.4", "Échographie"),
        new("VA", "1.2.840.10008.2.16.4", "Acuité visuelle"),
        new("XA", "1.2.840.10008.2.16.4", "Angiographie X-Ray"),
        new("XC", "1.2.840.10008.2.16.4", "Caméra de photographie externe"),
    };

    /// <summary>jdv-region-anatomique-cisis (1.2.250.1.213.1.1.5.695) : région anatomique SNOMED CT.</summary>
    public static readonly IReadOnlyList<Option> RegionAnatomique = new Option[]
    {
        new("63337009", "2.16.840.1.113883.6.96", "segment abdominopelvien du tronc"),
        new("38266002", "2.16.840.1.113883.6.96", "corps entier"),
        new("53120007", "2.16.840.1.113883.6.96", "membre supérieur"),
        new("61685007", "2.16.840.1.113883.6.96", "membre inférieur"),
        new("67734004", "2.16.840.1.113883.6.96", "segment thoracique du tronc"),
        new("774007", "2.16.840.1.113883.6.96", "tête et/ou cou"),
        new("113257007", "2.16.840.1.113883.6.96", "système cardiovasculaire"),
        new("80891009", "2.16.840.1.113883.6.96", "cœur"),
        new("76752008", "2.16.840.1.113883.6.96", "sein"),
        new("737561001", "2.16.840.1.113883.6.96", "colonne vertébrale et/ou moelle épinière"),
    };
}
