#!/usr/bin/env python3
"""Génère dotnet/demo/CdaCrImg.Demo/Form/JeuxDeValeurs.g.cs à partir des jeux de valeurs ANS du dépôt.

Usage : python3 tools/generate-demo-jdv.py
Sources : schematrons/profils/structurationMinimale/include/voc-*.xml (format ART-DECOR) et
jeuxDeValeurs/*.xml (format IHE SVS).
"""
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SM = os.path.join(ROOT, "schematrons/profils/structurationMinimale/include")
JDV = os.path.join(ROOT, "jeuxDeValeurs")
OUT = os.path.join(ROOT, "dotnet/demo/CdaCrImg.Demo/Form/JeuxDeValeurs.g.cs")

# (nom C#, fichier, format, description, filtre de système de codage)
SETS = [
    ("SecteurActivite", os.path.join(SM, "voc-1.2.250.1.213.1.1.5.467-DYNAMIC.xml"), "decor",
     "JDV_J04_XdsPracticeSettingCode_CISIS (1.2.250.1.213.1.1.5.467) : standardIndustryClassCode.", "1.2.250.1.213.1.1.4.9"),
    ("CadreExercice", os.path.join(SM, "voc-1.2.250.1.213.1.1.5.466-DYNAMIC.xml"), "decor",
     "JDV_J02_XdsHealthcareFacilityTypeCode_CISIS (1.2.250.1.213.1.1.5.466) : healthCareFacility/code.", "1.2.250.1.71.4.2.4"),
    ("TypeRencontre", os.path.join(SM, "voc-1.2.250.1.213.1.1.5.589-DYNAMIC.xml"), "decor",
     "JDV_J142_TypeRencontre_CISIS (1.2.250.1.213.1.1.5.589) : encompassingEncounter/code.", None),
    ("Civilite", os.path.join(SM, "voc-1.2.250.1.213.1.1.5.718-DYNAMIC.xml"), "decor",
     "JDV_J245_Civilite_CISIS (1.2.250.1.213.1.1.5.718) : name/prefix.", None),
    ("Titre", os.path.join(SM, "voc-1.2.250.1.213.1.1.5.719-DYNAMIC.xml"), "decor",
     "JDV_J246_Titre_CISIS (1.2.250.1.213.1.1.5.719) : name/suffix.", None),
    ("FonctionAuteur", os.path.join(SM, "voc-1.2.250.1.213.1.1.5.124-DYNAMIC.xml"), "decor",
     "JDV_J47_FunctionCode_CISIS (1.2.250.1.213.1.1.5.124) : author/functionCode.", "2.16.840.1.113883.5.88"),
    ("ModaliteAcquisition", os.path.join(JDV, "jdv-modalite-acquisition-cisis.xml"), "svs",
     "jdv-modalite-acquisition-cisis (1.2.250.1.213.1.1.5.618) : modalité d'acquisition DICOM.", None),
    ("RegionAnatomique", os.path.join(JDV, "jdv-region-anatomique-cisis.xml"), "svs",
     "jdv-region-anatomique-cisis (1.2.250.1.213.1.1.5.695) : région anatomique SNOMED CT.", None),
]


def concepts(path, fmt):
    tree = ET.parse(path)
    if fmt == "decor":
        return [(c.get("code"), c.get("codeSystem"), c.get("displayName")) for c in tree.iter("concept")]
    ns = "{urn:ihe:iti:svs:2008}"
    return [(c.get("code"), c.get("codeSystem"), c.get("displayName")) for c in tree.iter(ns + "Concept")]


def cs(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// <auto-generated>",
    "// Généré par tools/generate-demo-jdv.py à partir des jeux de valeurs ANS du dépôt : ne pas modifier.",
    "// </auto-generated>",
    "",
    "namespace CdaCrImg.Demo.Form;",
    "",
    "/// <summary>Jeux de valeurs ANS utilisés par les listes déroulantes du formulaire.</summary>",
    "public static class JeuxDeValeurs",
    "{",
]
for name, path, fmt, doc, system in SETS:
    items = [c for c in concepts(path, fmt) if system is None or c[1] == system]
    lines.append(f"    /// <summary>{doc}</summary>")
    lines.append(f"    public static readonly IReadOnlyList<Option> {name} = new Option[]")
    lines.append("    {")
    for code, codesystem, label in items:
        lines.append(f"        new({cs(code)}, {cs(codesystem)}, {cs(label)}),")
    lines.append("    };")
    lines.append("")
lines[-1] = "}"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"{OUT} : {len(SETS)} jeux de valeurs")
